version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 8002:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: dbadmin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8003:8080

volumes:
  db-data:
  keys:
