version: "3.1"

services:
  puts:
    image: putsweb
    restart: always
    ports:
      - 8000:5000
      - 8001:5001
    volumes:
      - keys:/app/Keys
    depends_on:
      - db
    environment:
      ConnectionStrings__ProblemDatabase: $ConnectionStrings__ProblemDatabase
      ASPNETCORE_URLS: https://+:5001;http://+:5000
  db:
    image: jsurf/rpi-mariadb
    restart: always
    ports:
      - 8002:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8003:8080

volumes:
  db-data:
  keys:
