version: "3.1"

services:
  puts:
    image: benasbudrys/putsweb
    restart: always
    ports:
      - 8000:5001
    volumes:
      - keys:/app/Keys
    depends_on:
      - db
    environment:
      ConnectionStrings__ProblemDatabase: $ConnectionStrings__ProblemDatabase
      ASPNETCORE_Kestrel__Certificates__Default__Password: $ASPNETCORE_Kestrel__Certificates__Default__Password
      ASPNETCORE_Kestrel__Certificates__Default__Path: $ASPNETCORE_Kestrel__Certificates__Default__Path
      ASPNETCORE_URLS: https://+:5001
  db:
    image: jsurf/rpi-mariadb
    restart: always
    ports:
      - 8001:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080

volumes:
  db-data:
  keys:
