version: "3.1"

services:
  puts:
    image: putsweb
    restart: always
    ports:
      - 8000:80
    volumes:
      - keys:/app/Keys
    depends_on:
      - db
    environment:
      ConnectionStrings__ProblemDatabase: server=db;user=root;password=dbadmin;database=puts
      ASPNETCORE_URLS: http://+:80
  db:
    image: jsurf/rpi-mariadb
    restart: always
    ports:
      - 8001:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dbadmin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080

volumes:
  db-data:
  keys:
