// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication;

namespace WebApplication.Migrations
{
    [DbContext(typeof(ProblemDbContext))]
    [Migration("20190915173120_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication.Models.Problem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("InputDescription")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OutputDescription")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("WebApplication.Models.Test", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExpectedOutput")
                        .IsRequired();

                    b.Property<string>("GivenInput");

                    b.Property<int?>("ProblemID");

                    b.HasKey("ID");

                    b.HasIndex("ProblemID");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("WebApplication.Models.Test", b =>
                {
                    b.HasOne("WebApplication.Models.Problem")
                        .WithMany("Tests")
                        .HasForeignKey("ProblemID");
                });
#pragma warning restore 612, 618
        }
    }
}
